# Rutas del proyecto.
# Si cambias de ordenador o mueves las carpetas, solo tienes que modificar esto.
ruta_pdfs_por_asignatura: "C:/Users/ernes/OneDrive/Desktop/UNI/UPM/5/TFG/Recopilacion documentos para TFG/Todo por cursos"
modelo: "gemini-2.5-flash"
pregunta: "¿Qué asignaturas tienen simultáneamente examen final >40% y prácticas obligatorias?"
